src/Entity/Article.php
<?php
/**
 * Created by PhpStorm.
 * User: Roma
 * Date: 06/05/2018
 * Time: 14:55
 */

namespace App\Entity;


use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Entity
 * @ORM\Table(name="articles")
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $articleName;

    /**
     * @ORM\Column(type="datetime", nullable=false)
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=false)
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Lecture", inversedBy="articles")
     */
    private $lecture;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="articles")
     */
    private $users;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="teachersActicles")
     */
    private $teacher_article;


    /**
     * @ORM\Column(type="integer")
     */
    private $views = 0;

/////////////////////////////////////<-getters & setters->/////////////////////////////////////////

    public function getViews()
    {
        return $this->views;
    }


    public function setViews($views): void
    {
        $this->views = $views;
    }



    public function getUsers()
    {
        return $this->users;
    }


    public function setUsers($users): void
    {
        $this->users = $users;
    }


    public function getLecture()
    {
        return $this->lecture;
    }


    public function setLecture($lecture): void
    {
        $this->lecture = $lecture;
    }



    public function getId()
    {
        return $this->id;
    }


    public function getArticleName()
    {
        return $this->articleName;
    }


    public function setArticleName($articleName): void
    {
        $this->articleName = $articleName;
    }


    public function getCreatedAt()
    {
        return $this->createdAt;
    }


    public function setCreatedAt($createdAt): void
    {
        $this->createdAt = $createdAt;
    }


    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }


    public function setUpdatedAt($updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }


    public function getTeacherArticle(): ?User
    {
        return $this->teacher_article;
    }


    public function setTeacherArticle(User $teacher_article): self
    {
        $this->teacher_article = $teacher_article;

        return $this;
    }

/////////////////////////<-custom functions->////////////////////////////////////////
    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function  updateTimestamps(): void
    {
        $dateTimeNow = new DateTime('now');
        $this->setUpdatedAt($dateTimeNow);
        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt($dateTimeNow);
        }
    }

    public function __toString()
    {
        return $this->getArticleName();

    }






}

src/Entity/User.php
<?php
/**
 * Created by PhpStorm.
 * User: Roma
 * Date: 02/05/2018
 * Time: 10:40
 */

namespace App\Entity;


use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="app_users")
 * @UniqueEntity(fields={"email"}, message="Email all ready exists!")
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     */
    private $firstName;


    /**
     * @ORM\Column(type="string")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string")
     */
    private $password;

    private $plainPassword;

    /**
     *
     * @ORM\Column(type="datetime", nullable=false)
     */
    private $createdAt;

    /**
     *
     * @ORM\Column(type="datetime", nullable=false)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="simple_array", nullable=true)
     */
    private $roles = ['ROLE_STUDENT'];

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Lecture", mappedBy="users")
     */
    private $lectures;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Article", mappedBy="users")
     */
    private $articles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Lecture", mappedBy="teacher")
     */
    private $teachersLectures;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Article", mappedBy="teacher_article")
     */
    private $teachersArticles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Grade", mappedBy="student")
     */
    private $studentGrades;


    /**
     * @ORM\Column(type="decimal", scale=2, nullable=true)
     */
    private $totalGrade;





/////////////////////////////////  <-construct->  /////////////////////////////////////////////////////

    public function __construct()
    {
        $this->teachersArticles = new ArrayCollection();
        $this->teachersLectures = new ArrayCollection();
        $this->lectures = new ArrayCollection();
        $this->articles = new ArrayCollection();
        $this->studentGrades = new ArrayCollection();

    }



////////////////////////////    <- getter & setters ->    /////////////////////////////////////////////


    public function getTotalGrade()
    {
        return $this->totalGrade;
    }


    public function setTotalGrade($totalGrade): void
    {
        $this->totalGrade = $totalGrade;
    }

    /**
     * @return ArrayCollection|Grade[]
     */
    public function getStudentGrades()
    {
        return $this->studentGrades;
    }


    public function setStudentGrades($studentGrades): void
    {
        $this->studentGrades = $studentGrades;
    }



    public function getLastName()
    {
        return $this->lastName;
    }


    public function setLastName($lastName): void
    {
        $this->lastName = $lastName;
    }

    public function getUsername()
    {
        return $this->email;
    }


    public function getEmail()
    {
        return $this->email;
    }


    public function setEmail($email): void
    {
        $this->email = $email;
    }


    public function getFirstName()
    {
        return $this->firstName;
    }


    public function setFirstName($firstName): void
    {
        $this->firstName = $firstName;
    }


    public function getPassword()
    {
        return $this->password;
    }


    public function setPassword($password): void
    {
        $this->password = $password;
    }


    public function getPlainPassword()
    {
        return $this->plainPassword;
    }


    public function setPlainPassword($password): void
    {
        $this->plainPassword = $password;
    }


    public function getCreatedAt()
    {
        return $this->createdAt;
    }


    public function setCreatedAt($createdAt): void
    {
        $this->createdAt = $createdAt;
    }


    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }


    public function setUpdatedAt($updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }



    public function setRoles($roles)
    {
       $this->roles = $roles;

    }

    public function getRoles()
    {
        $temRoles = $this->roles;

        if(!in_array('ROLE_STUDENT' || 'ROLE_TEACHER', $temRoles)){
            $temRoles[] = 'ROLE_STUDENT';
        }
        return $temRoles;
    }


    public function getId()
    {
        return $this->id;
    }


    public function getArticles()
    {
        return $this->articles;
    }


    public function setArticles($articles): void
    {
        $this->articles = $articles;
    }


    public function getLectures()
    {
        return $this->lectures;
    }

    /**
     * @return ArrayCollection|Lecture[]
     */
    public function getTeachersLectures()
    {
        return $this->teachersLectures;
    }


    /**
     * @return ArrayCollection|Article[]
     */
    public function getTeachersArticles()
    {
        return $this->teachersArticles;
    }

    public function getSalt()
    {
        return null;
    }

///////////////////////////////<-custom functions->/////////////////////////////////////////////
    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function  updateTimestamps(): void
    {
        $dateTimeNow = new DateTime('now');
        $this->setUpdatedAt($dateTimeNow);
        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt($dateTimeNow);
        }
    }


    public function eraseCredentials()
    {
        return null;
    }

    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->email,
            $this->password,
        ));
    }

    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->email,
            $this->password,
            ) = unserialize($serialized, ['allowed_classes' => false]);
    }


    public function getFullName()
    {
        return trim($this->getFirstName().' '.$this->getLastName());
    }


    public function __toString()
    {
        return $this->getFullName();
    }



}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Lecture;
use App\Repository\LectureRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('articleName')
            ->add('Lecture', EntityType::class, [
                'placeholder' => 'Lecture',
                'class' => Lecture::class,
                'query_builder' => function(LectureRepository $repo){
                    return $repo->createLectureQueryBuilder();
                }
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\User;
use App\Form\ArticleType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/article")
 */
class ArticleController extends Controller
{
    /**
     * @Route("/", name="article_index", methods="GET")
     */
    public function index(): Response
    {
        $teacherId = $this->getUser()->getId();
        $user = $this->getUser()->getUsername();
        $articles = $this->getDoctrine()
            ->getRepository(Article::class)
            ->findBy(['teacher_article' => $teacherId]);

        return $this->render('article/index.html.twig', [
            'articles' => $articles,
            'user' => $user
        ]);
    }

    /**
     * @Route("/new", name="article_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {

        $article = new Article();
        $user = $this->getUser();
        $article->setTeacherArticle($user);

        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($article);
            $em->flush();

            return $this->redirectToRoute('article_index');
        }

        return $this->render('article/new.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_show", methods="GET|POST")
     */
    public function show(Article $article): Response
    {
        $views = $article->getViews();
        $article->setViews($views + 1);
        $em = $this->getDoctrine()->getManager();
        $em->persist($article);
        $em->flush();


        $user = $this->getUser()->getUsername();

        return $this->render('article/show.html.twig', [
            'article' => $article,
            'user' => $user
        ]);
    }

    /**
     * @Route("/{id}/edit", name="article_edit", methods="GET|POST")
     */
    public function edit(Request $request, Article $article): Response
    {
        $user = $this->getUser();
        $this->denyAccessUnlessGranted('edit', $user);
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('article_edit', ['id' => $article->getId()]);
        }

        return $this->render('article/edit.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_delete", methods="DELETE")
     */
    public function delete(Request $request, Article $article, User $user): Response
    {
        $this->denyAccessUnlessGranted('delete', $user);
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($article);
            $em->flush();
        }

        return $this->redirectToRoute('article_index');
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn">Delete</button>
</form>

templates/article/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Article{% endblock %}

{% block body %}
    <h1>Edit Article</h1>

    {{ include('article/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('article_index') }}">back to list</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article index{% endblock %}

{% block body %}
    <h1>Article index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Article</th>
                <th>Created By</th>
                <th>CreatedAt</th>
                <th>UpdatedAt</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <td>{{ article.id }}</td>
                <td>{{ article.articleName }}</td>
                <td>{{ article.teacherArticle.fullName|default('undefined') }}</td>
                <td>{{ article.createdAt ? article.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ article.updatedAt ? article.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('article_show', {'id': article.id}) }}">show</a>
                    {% if article.teacherArticle.email  is same as(user) or is_granted('ROLE_ADMIN')%}
                        <a href="{{ path('article_edit', {'id': article.id}) }}">edit</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_granted('ROLE_TEACHER') %}
        <a href="{{ path('article_new') }}">Create new</a>
    {% endif %}
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Article{% endblock %}

{% block body %}
    <h1>Create new Article</h1>

    {{ include('article/_form.html.twig') }}

    <a href="{{ path('article_index') }}">back to list</a>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
    <h1>Article</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ article.id }}</td>
            </tr>
            <tr>
                <th>ArticleName</th>
                <td>{{ article.articleName }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ article.createdAt ? article.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>UpdatedAt</th>
                <td>{{ article.updatedAt ? article.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('article_index') }}">back to list</a>
    <br>
    {% if article.teacherArticle.email  is same as(user) or is_granted('ROLE_ADMIN')%}
        <a href="{{ path('article_edit', {'id': article.id}) }}">edit</a>
        <br>
        {{ include('article/_delete_form.html.twig') }}
    {% endif %}
{% endblock %}